# NumPy Basics

* NumPy stands for Numerical Python and also known as array oriented computing.
* NumPy is a library written for scientific computing and data analysis.
* NumPy consists of a powerful data structure called multidimensional arrays.
* The most basic object in Numpy is the ndarray, or simply an array which is an n-dimensional, homogeneous array. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which is commonly numeric (float or integer).


 # Why NumPy?
 * convenience & speed
 
 * NumPy is much faster than the standard python ways to do computations.
 
 * We don't have to do the explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

 * NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists

#### Install numpy library

In [2]:
!pip install numpy

#### Importing numpy library

In [3]:
import numpy as np

#### creating array using .array() method

In [4]:
#Ex1) 
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [4]:
# to check the type
type(arr)

numpy.ndarray

#### to get the dimension

In [5]:
arr.shape

(3,)

#### to get the data types of the array elements

In [6]:
arr.dtype

dtype('int32')

In [7]:
#Ex2) 2d array
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
type(b)

numpy.ndarray

In [9]:
b.shape

(3, 3)

In [10]:
b.dtype

dtype('int32')

In [11]:
#we have a list
lst_1 = [i for i in range(10)]
lst_1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
# to add value 2 to all the elements

#1) normal method
# lst_2 = []
# for item in lst_1:
#     lst_2.append(item + 2)
# print(lst_2)

#2) list comprehension
lst_2 = [i+2 for i in lst_1]
print(lst_2)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


#### Numpy will do elementwise calculations

In [13]:
# arange() is similar to range()
np_arr1 = np.arange(10)
np_arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np_arr2 = np_arr1 + 2
np_arr2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Performance measurement

**%timeit** is an python function, which can be used to check the time taken by a particular piece of code (A single execution statement, or a single method)

#### Ex1) Time taken by the normal lists to do a task

In [15]:
%timeit [i**3 for i in range(10000)]

617 μs ± 4.92 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


#### Time taken by Numpy arrays to do the same task

In [16]:
%timeit np.arange(10000)**3

15.9 μs ± 75.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### Ex2) Time taken to multiply two lists elementwise

In [17]:
l1 = [i for i in range(10000)]
l2 = [i**2 for i in range(10000)]

In [18]:
%timeit list(map(lambda x, y: x*y, l1, l2))

577 μs ± 5.84 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


#### Time taken by Numpy arrays to do the same task

In [19]:
a1 = np.arange(10000)
b1 = np.arange(10000)**2

In [20]:
%timeit a1*b1

3.41 μs ± 103 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Creating Numpy arrays

#### np.array(list)

In [21]:
#Ex 1)
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [22]:
#Ex 2)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


#### np.arange(start,stop,step)

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
np.arange(21,0,-2)

array([21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

#### np.zeros(shape)

In [27]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.zeros((3,3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
np.zeros(1, dtype=np.int32) #vector

array([0])

In [30]:
np.zeros((1,1), dtype=np.int32) #matrix

array([[0]])

#### np.zeros_like(ndarray)

In [31]:
a = np.array([[2, 3], [2, 4], [8, 9]])
print(a)
print(a.shape)

[[2 3]
 [2 4]
 [8 9]]
(3, 2)


In [32]:
np.zeros_like(a)

array([[0, 0],
       [0, 0],
       [0, 0]])

#### np.ones(shape)

In [33]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [35]:
np.ones(1, dtype=np.int32) #vector

array([1])

In [36]:
np.ones((1,1), dtype=np.int32) #matrix

array([[1]])

#### np.ones_like(ndarray)

In [37]:
a = np.array([[2, 3], [2, 4], [8, 9]])
print(a)
print(a.shape)

[[2 3]
 [2 4]
 [8 9]]
(3, 2)


In [38]:
np.ones_like(a)

array([[1, 1],
       [1, 1],
       [1, 1]])

#### np.full(shape,value)

In [39]:
np.full((5, 3), 3.3)

array([[3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3]])

In [40]:
np.full((2, 4),  3.7, dtype=np.int32)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

#### np.eye(m) : this method is used to create identity matrix , here m = n

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
np.eye(4,dtype=np.int32)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

#### np.diag(list) : is used to create diagonal matrix

In [43]:
np.diag([2, 5, 68, 78])

array([[ 2,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 68,  0],
       [ 0,  0,  0, 78]])

In [44]:
np.diag(np.arange(1,16,2))

array([[ 1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  9,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 11,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 13,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 15]])

# Accessing and Slicing Numpy array elements

### 1D arrays

In [45]:
a = np.array([2,4,6,8,10,12,14,16])
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [46]:
# accessing first element
a[0]

2

In [47]:
# accessing third element
a[2]

6

In [48]:
# accessing last element
a[-1]

16

In [49]:
# accessing multiple elements
a[[0,2,4]]

array([ 2,  6, 10])

In [50]:
# slicing
# to get all the elements from 2nd index
a[2:]

array([ 6,  8, 10, 12, 14, 16])

In [51]:
# to get all the alternate elements
a[::2]

array([ 2,  6, 10, 14])

### n-dimension array

In [52]:
# consider we have 2D array
a = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11],[12, 13, 14, 15]])

In [53]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
# to access 10
# a[rowIndex,columnIndex]

a[2,2]

10

In [55]:
# to access 13
a[3,1]

13

In [56]:
# to get 0,1,4,5
a[0:2, 0:2] 

array([[0, 1],
       [4, 5]])

In [57]:
# to get 10,11,14,15
a[2:,2:]

array([[10, 11],
       [14, 15]])

In [58]:
# similarly to get 5,6,9,10
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [59]:
# to check which elements are greater than 5
a>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [60]:
# to get the elements that are greater than 5
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [61]:
# to get the elements between 5 to 10
a[(a > 5) & (a < 10)]

array([6, 7, 8, 9])

# Copying and modifying the numpy arrays

In [62]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
b = a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
b[0] = 100

In [65]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [66]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

##### shares_memory()
this method checks if both the arrays shares the same memory

In [67]:
np.shares_memory(a,b)

True

#### .copy()

In [68]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = a.copy()
b

In [69]:
b[0] = 100

In [70]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [71]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
np.shares_memory(a,b)

False